theme = "catppuccin_mocha"
# see this on how to use this theme -> https://github.com/catppuccin/helix

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
